version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: gym-db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
